
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['POSTGRES_HOST'] %>
  port: 5432

development:
  <<: *default
  database: homify_api_development
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>


test:
  <<: *default
  database: homify_api_test


production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  database: homify
  username: homify_user
  password: <%= ENV["HOMIFY_API_DATABASE_PASSWORD"] %>
